const BankData = [
  { id: "0005", name: "三菱UFJ銀行", ischeck: false },
  { id: "0009", name: "三井住友銀行", ischeck: false },
  { id: "0001", name: "みずほ銀行", ischeck: false },
  { id: "0010", name: "りそな銀行", ischeck: false },
  { id: "9900", name: "ゆうちょ銀行", ischeck: false },
  { id: "0038", name: "住信SBIネット銀行", ischeck: false },
  { id: "0036", name: "楽天銀行", ischeck: false },
  { id: "0033", name: "ジャパンネット銀行", ischeck: false },
  { id: "0040", name: "イオン銀行", ischeck: false },
  { id: "0035", name: "ソニー銀行", ischeck: false },
  { id: "0397", name: "新生銀行", ischeck: false },
  { id: "", name: "その他", ischeck: false },
];

const TODOHUKENN = [
  { value: "北海道" },
  { value: "青森県" },
  { value: "岩手県" },
  { value: "宮城県" },
  { value: "秋田県" },
  { value: "山形県" },
  { value: "福島県" },
  { value: "茨城県" },
  { value: "栃木県" },
  { value: "群馬県" },
  { value: "埼玉県" },
  { value: "千葉県" },
  { value: "東京都" },
  { value: "神奈川県" },
  { value: "新潟県" },
  { value: "富山県" },
  { value: "石川県" },
  { value: "福井県" },
  { value: "山梨県" },
  { value: "長野県" },
  { value: "岐阜県" },
  { value: "静岡県" },
  { value: "愛知県" },
  { value: "三重県" },
  { value: "滋賀県" },
  { value: "京都府" },
  { value: "大阪府" },
  { value: "兵庫県" },
  { value: "奈良県" },
  { value: "和歌山県" },
  { value: "鳥取県" },
  { value: "島根県" },
  { value: "岡山県" },
  { value: "広島県" },
  { value: "山口県" },
  { value: "徳島県" },
  { value: "香川県" },
  { value: "愛媛県" },
  { value: "高知県" },
  { value: "福岡県" },
  { value: "佐賀県" },
  { value: "長崎県" },
  { value: "熊本県" },
  { value: "大分県" },
  { value: "宮崎県" },
  { value: "鹿児島県" },
  { value: "沖縄県" },
];

const GYOUSYU = [
  { value: "農業/林業/漁業" },
  { value: "製造業" },
  { value: "建設業" },
  { value: "情報通信業" },
  { value: "運輸業" },
  { value: "卸売/小売業" },
  { value: "金融業/保険業" },
  { value: "不動産業" },
  { value: "サービス業" },
  { value: "信託会社" },
  { value: "貸金業" },
  { value: "資金移動業" },
  { value: "仮想通貨交換業" },
  { value: "両替業" },
  { value: "ファイナンスリース事業" },
  { value: "クレジットカード事業" },
  { value: "宅地建物取引業" },
  { value: "宝石・貴金属等取扱事業" },
  {
    value: "郵便物受取サービス業・電話受付代行業・電話転送サービス事業",
  },
  {
    value: "弁護士法人・司法書士法人・行政書士法人・監査法人・税理士法人",
  },
  { value: "NPO(非営利団体)" },
  { value: "娯楽業" },
  { value: "その他" },
];
const MALE = 1;
const FEMALE = 2;

//不需要银行两个字的
const specialBank = [
  "農協",
  "信金",
  "信組",
  "信連",
  "信漁連",
  "労金",
  "信託",
  "漁協",
  "金庫",
];

export default {
  BankData,

  TODOHUKENN,
  GYOUSYU,
  MALE,
  FEMALE,
  specialBank,
};
